zeptomail/__init__.py,sha256=KyA6ghxkHioF98QHPbXuFlKV09gD35VEVgmqID3nmKw,279
zeptomail/client.py,sha256=PzpwgeOBwVPdib8TympiPVpBEoYqJfLhb1YRfJiolqo,15773
zeptomail/errors.py,sha256=KTcwp0FQOwbm8l2fOMf7ZgtVDRfbFJk4Ei0m8Nvxl9Q,5161
zeptomail/webhooks/__init__.py,sha256=z6E2ALQz9inaR3fCFgJJZLujkneyBB4YQPMGFTsEQvI,310
zeptomail/webhooks/models.py,sha256=9zI9AbLr0-SaY4K37mLJ8eDAembPgikA4gHfIgOf2zE,2623
zeptomail/webhooks/router.py,sha256=w7eBquioKosrOmt0EXqXqkhlp1_cHRD1L381jhmIN6A,3303
zeptomail_python_api-0.1.3.dist-info/METADATA,sha256=yyYC9xgvf4uFvk1WL9bTvJsKyy3ctkp15w_CqCZOuug,7261
zeptomail_python_api-0.1.3.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
zeptomail_python_api-0.1.3.dist-info/licenses/LICENSE,sha256=FHu33Y3OXu91zSZRTECumVQGMSVMlO3S1bV3n3B9HMA,1070
zeptomail_python_api-0.1.3.dist-info/RECORD,,
