zeptomail/__init__.py,sha256=25ISoFUJgxQhEJURijlSTf0f76FOqXRtJHyyv-QBeYc,112
zeptomail/client.py,sha256=B3ooHPlNNU6HnbNS7prVhP_W0GGPQCn_gtGvwaBED-8,16458
zeptomail/errors.py,sha256=rGkw9-JzfWTn-GtKNys9emQsca5WX4NctFHOeXADvx4,1309
zeptomail_python_api-0.1.1.dist-info/METADATA,sha256=DRzm2yOqelYt1WuvR7vOTZuEEwULlVA928EpEmyWEFE,4659
zeptomail_python_api-0.1.1.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
zeptomail_python_api-0.1.1.dist-info/licenses/LICENSE,sha256=FHu33Y3OXu91zSZRTECumVQGMSVMlO3S1bV3n3B9HMA,1070
zeptomail_python_api-0.1.1.dist-info/RECORD,,
